### PR TITLE
July 2022 edition

### PR DESCRIPTION
**Pull request by ceenell**
flow_cartogram

### CODE REVIEW

**Comment by ceenell** [comment]
What's weird is that the onion skin view of the changing png between this month and last shows a shift in the layout

**Comment by aaarchmiller** [comment]
That is weird that it shows a shifting layout. On mine, when I compare them side by side, July's are vertically squished just a bit. I don't understand how that would change from last month?

**Review by aaarchmiller — APPROVED** [review]
Other than the shifting layout, it looks good and ran on my computer. It did still have the shifting size after I ran it too. So weird!

**Comment by ceenell** [comment]
very strange but going to merge it

**Pull request merged**
